### ISSUE TITLE
App closing when clicking on some of the particles' name

### ISSUE THREAD

**Issue by AngeloSantos** [umello/Issues-TheParticles-Android#5]
**Describe the bug**
App closing when clicking on some of the particles' name.

**To Reproduce**
1. Go to Barions (or Mesons)
2. Click on any particle in the vertical list
3. It forces the App to close

**Expected behavior**
It would be expected to move to a "page" with with images and text about the correspondent particle.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device Model: Motorola G6 Play
 - Android Version 9

**Additional context**

**Comment by umello** [comment]
Mesons: fixed a minor mistake on the Portuguese translation files;
Barions: fixed a bug on the code responsible to build the path to the particle group data.
