### ISSUE TITLE
Scrolling down to empty text or incomplete text

### ISSUE THREAD

**Issue by AngeloSantos** [umello/Issues-TheParticles-Android#6]
**Describe the bug**
Scrolling down to the end of the text leads to empty text or incomplete text.

**To Reproduce**
1. Go to any group in the pizza image
2. Click on any of the particles in the vertical list
3. Scroll down to the end of the text
4. Some times, we can keep scrolling down, even if there is no text; some times, some paragraphs (in the end) seems to be incomplete (or seems that the text is continue the right side of the page); and some times, no text appears.

**Expected behavior**
We expect that scrolling down to end of the text without scrolling down indefinitely, and that the paragraphs finish appropriately. 

**Screenshots**
I included 2 images.
![Empty_text](https://user-images.githubusercontent.com/5694403/82568578-6a875180-9b55-11ea-9aa4-cbfb8083e9c5.jpeg)
![Incomplete_text](https://user-images.githubusercontent.com/5694403/82568580-6b1fe800-9b55-11ea-9100-4c016f8ecf75.jpeg)

**Smartphone (please complete the following information):**
 - Device Model: Motorola G6 Play
 - Android Version 9

**Additional context**
This behavior is intermittent. Some times, the text is ok. But some times, we can keep scrolling down, even if there is no text; some times, some paragraphs (in the end) seems to be incomplete (or seems that the text is continue to the right side of the page); and some times, no text appears.

**Comment by umello** [comment]
This is happening because some of the tags <nobr> lost their closing counterparts </nobr> in the translated content. I'll close this issue when we are done restoring them.

**Comment by umello** [comment]
Fixed
